version: "3.1"

services:
  api:
    restart: always
    environment:
      - "PORT=8000"
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    image: generic-api:dev
    working_dir: /generic-api
    tty: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/generic-api
    command: air
